/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tank_com_kotlin_ndk_BsPatchApi */

#ifndef _Included_tank_com_kotlin_ndk_BsPatchApi
#define _Included_tank_com_kotlin_ndk_BsPatchApi

#include <"bs_patch.h">

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     tank_com_kotlin_ndk_BsPatchApi
 * Method:    doPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_tank_com_kotlin_ndk_BsPatchApi_doPatch
  (JNIEnv *env, jobject, jstring, jstring, jstring){
    print("Java_tank_com_kotlin_ndk_BsPatchApi_doPatch ::: ");
  }

#ifdef __cplusplus
}
#endif
#endif
